### ISSUE TITLE
哈哈哈哈哈哈嗝

### ISSUE THREAD

**Issue by KiteAB** [chitang233/dot-files#3]
这vimium c配置给我整笑了  cw配置强行搬过来  pageUp: "u" pageDown: "e"

哈哈哈哈嗝

**Comment by chitang233** [comment]
这几天懒得折腾nvim了
然后干脆用你的nvim配置
然后为了统一
就自己赣了个vimium c配置
有什么问题吗?

**Comment by KiteAB** [comment]
> 这几天懒得折腾nvim了
> 然后干脆用你的nvim配置
> 然后为了统一
> 就自己赣了个vimium c配置
> 有什么问题吗?

不是  向上翻页是u   向下是e   离谱   宁未必用colemak？

**Comment by chitang233** [comment]
不用colemak啊
u e习惯了以后在qwerty上也挺不错的啊

**Comment by KiteAB** [comment]
???????这比hjkl都难适应

**Comment by chitang233** [comment]
好家伙那就是你的问题了

**Comment by KiteAB** [comment]
hack.chat/?wdnmd  @chitang233
